  on: [push, pull_request]
name: Bot Linting
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"
      - run: npm install
        working-directory: website
      - run: npm run lint
        working-directory: website